name: Scheduled Update

on:
  workflow_dispatch:  # Manual trigger
  schedule:           # Scheduled trigger
    - cron: '0 * * * *'  # Run every 60 minutes

jobs:
  update-rss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feed_number: [1, 2, 3, 4]
        start_page: [1]
        end_page: [1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests pytz

    - name: Run update script
      run: python rssfeed.py ${{ matrix.feed_number }} ${{ matrix.start_page }} ${{ matrix.end_page }}

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add rssfeed/*.xml
        git commit -m "Update RSS feed" || echo "No changes to commit"
        git pull origin main --rebase
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
